### ISSUE TITLE
Can not create a tab with ckeditor full features

### ISSUE THREAD

**Issue by san3jaya** [sealocal/ckeditor-bootstrap-tabs#10]
We cant use this plugin with full features. it work with standered features.

![1](https://cloud.githubusercontent.com/assets/8122779/14141430/8bf56c2e-f69c-11e5-9eb2-5052f5ec708b.JPG)

**Comment by sealocal** [comment]
Are you using v1.1 from the CKEditor add-ons page?

http://ckeditor.com/addon/bootstrapTabs
