### ISSUE TITLE
Deleting a tab

### ISSUE THREAD

**Issue by TCURT15** [sealocal/ckeditor-bootstrap-tabs#13]
I am getting an error when trying to remove a tab. The error is "bootstrapTabs.js?t=G14E:153 Uncaught TypeError: Cannot read property 'find' of null" and occurs on line "tabPanelElements = tabContentElement.find( 'div.tab-pane' );".

**Comment by sealocal** [comment]
I suppose you're missing the tab-pane div. Care to upload the raw HTML from your editor?

**Comment by TCURT15** [comment]
<div class="col-lg-9 col-xs-12">
   <section>
      <div class="bootstrap-tabs" data-tab-set-title="tabs">
         <ul class="nav nav-tabs nav-justified" role="tablist">
            
            <li role="presentation"><a aria-controls="tabs-tab-1" aria-expanded="false" class="tab-link" data-toggle="tab" href="#tabs-tab-1" role="tab">Tab 1</a></li>
            <li role="presentation"><a aria-controls="tabs-tab-2" aria-expanded="false" class="tab-link" data-toggle="tab" href="#tabs-tab-2" role="tab">Tab 2</a></li>
            <li class="active" role="presentation"><a aria-controls="tabs-tab-3" aria-expanded="true" class="tab-link" data-toggle="tab" href="#tabs-tab-3" role="tab">Tab 3</a></li>
            <li role="presentation"><a aria-controls="tabs-tab-4" aria-expanded="false" class="tab-link" data-toggle="tab" href="#tabs-tab-4" role="tab">Tab 4</a></li>
         </ul>
      </div>
      <div class="tab-content">
         
         <div class="tab-pane" id="tabs-tab-1" role="tabpanel">
            <div class="tab-pane-content">
               <h3>&nbsp;</h3>
               <h3>Quick Links</h3>
               <div class="row">
                  <div class="col-xs-12 col-md-4">
                     <div class="panel panel-widget panel-orange">
                        <div class="panel-heading" style="height: 112px;">
                           <div class="row">
                              <div class="col-xs-12">
                                <p>Content</p>
                              </div>
                           </div>
                        </div>
                        <div class="panel-footer">
                           <div class="clearfix">&nbsp;</div>
                        </div>
                     </div>
                  </div>
                  <div class="col-md-4 col-xs-12">
                     <div class="panel panel-widget panel-red">
                        <div class="panel-heading" style="height: 112px;">
                           <div class="row">
                              <div class="col-xs-12">
                                <p>Content</p>
                              </div>
                              <div class="icon fa fa-file fa-3x">&nbsp;</div>
                           </div>
                        </div>
                        <div class="panel-footer">
                           <div class="clearfix">&nbsp;</div>
                        </div>
                     </div>
                  </div>
                  <div class="col-xs-12 col-md-4">
                     <div class="panel panel-widget panel-green">
                        <div class="panel-heading" style="height: 112px;">
                           <div class="row">
                              <div class="col-xs-12">
                              	<p>Content</p>
                              </div>
                              <div class="icon fa fa-key fa-3x">&nbsp;</div>
                           </div>
                        </div>
                        <div class="panel-footer">
                           <div class="clearfix">&nbsp;</div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="tab-pane" id="tabs-tab-2" role="tabpanel">
            <div class="tab-pane-content">
               <div class="row">
                  <div class="col-xs-12">
                  	<p>Content</p>
                  </div>
               </div>
            </div>
         </div>
         <div class="tab-pane active" id="tabs-tab-3" role="tabpanel">
            <div class="tab-pane-content">
               <p>Content</p>
            </div>
         </div>
         <div class="tab-pane" id="tabs-tab-4" role="tabpanel">
            <div class="tab-pane-content">Tab 4 Content</div>
         </div>
      </div>
   </section>
</div>``

**Comment by TCURT15** [comment]
<div class="col-lg-9 col-xs-12">
   <section>
      <div class="bootstrap-tabs" data-tab-set-title="tabs">
         <ul class="nav nav-tabs nav-justified" role="tablist">
            
            <li role="presentation"><a aria-controls="tabs-tab-1" aria-expanded="false" class="tab-link" data-toggle="tab" href="#tabs-tab-1" role="tab">Tab 1</a></li>
            <li role="presentation"><a aria-controls="tabs-tab-2" aria-expanded="false" class="tab-link" data-toggle="tab" href="#tabs-tab-2" role="tab">Tab 2</a></li>
            <li class="active" role="presentation"><a aria-controls="tabs-tab-3" aria-expanded="true" class="tab-link" data-toggle="tab" href="#tabs-tab-3" role="tab">Tab 3</a></li>
            <li role="presentation"><a aria-controls="tabs-tab-4" aria-expanded="false" class="tab-link" data-toggle="tab" href="#tabs-tab-4" role="tab">Tab 4</a></li>
         </ul>
      </div>
      <div class="tab-content">
         
         <div class="tab-pane" id="tabs-tab-1" role="tabpanel">
            <div class="tab-pane-content">
               <h3>&nbsp;</h3>
               <h3>Quick Links</h3>
               <div class="row">
                  <div class="col-xs-12 col-md-4">
                     <div class="panel panel-widget panel-orange">
                        <div class="panel-heading" style="height: 112px;">
                           <div class="row">
                              <div class="col-xs-12">
                                <p>Content</p>
                              </div>
                           </div>
                        </div>
                        <div class="panel-footer">
                           <div class="clearfix">&nbsp;</div>
                        </div>
                     </div>
                  </div>
                  <div class="col-md-4 col-xs-12">
                     <div class="panel panel-widget panel-red">
                        <div class="panel-heading" style="height: 112px;">
                           <div class="row">
                              <div class="col-xs-12">
                                <p>Content</p>
                              </div>
                              <div class="icon fa fa-file fa-3x">&nbsp;</div>
                           </div>
                        </div>
                        <div class="panel-footer">
                           <div class="clearfix">&nbsp;</div>
                        </div>
                     </div>
                  </div>
                  <div class="col-xs-12 col-md-4">
                     <div class="panel panel-widget panel-green">
                        <div class="panel-heading" style="height: 112px;">
                           <div class="row">
                              <div class="col-xs-12">
                              	<p>Content</p>
                              </div>
                              <div class="icon fa fa-key fa-3x">&nbsp;</div>
                           </div>
                        </div>
                        <div class="panel-footer">
                           <div class="clearfix">&nbsp;</div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="tab-pane" id="tabs-tab-2" role="tabpanel">
            <div class="tab-pane-content">
               <div class="row">
                  <div class="col-xs-12">
                  	<p>Content</p>
                  </div>
               </div>
            </div>
         </div>
         <div class="tab-pane active" id="tabs-tab-3" role="tabpanel">
            <div class="tab-pane-content">
               <p>Content</p>
            </div>
         </div>
         <div class="tab-pane" id="tabs-tab-4" role="tabpanel">
            <div class="tab-pane-content">Tab 4 Content</div>
         </div>
      </div>
   </section>
</div>

**Comment by TCURT15** [comment]
<div class="col-lg-9 col-xs-12">
   <section>
      <div class="bootstrap-tabs" data-tab-set-title="tabs">
         <ul class="nav nav-tabs nav-justified" role="tablist">
            
            <li role="presentation"><a aria-controls="tabs-tab-1" aria-expanded="false" class="tab-link" data-toggle="tab" href="#tabs-tab-1" role="tab">Tab 1</a></li>
            <li role="presentation"><a aria-controls="tabs-tab-2" aria-expanded="false" class="tab-link" data-toggle="tab" href="#tabs-tab-2" role="tab">Tab 2</a></li>
            <li class="active" role="presentation"><a aria-controls="tabs-tab-3" aria-expanded="true" class="tab-link" data-toggle="tab" href="#tabs-tab-3" role="tab">Tab 3</a></li>
            <li role="presentation"><a aria-controls="tabs-tab-4" aria-expanded="false" class="tab-link" data-toggle="tab" href="#tabs-tab-4" role="tab">Tab 4</a></li>
         </ul>
      </div>
      <div class="tab-content">
         
         <div class="tab-pane" id="tabs-tab-1" role="tabpanel">
            <div class="tab-pane-content">
               <h3>&nbsp;</h3>
               <h3>Quick Links</h3>
               <div class="row">
                  <div class="col-xs-12 col-md-4">
                     <div class="panel panel-widget panel-orange">
                        <div class="panel-heading" style="height: 112px;">
                           <div class="row">
                              <div class="col-xs-12">
                                <p>Content</p>
                              </div>
                           </div>
                        </div>
                        <div class="panel-footer">
                           <div class="clearfix">&nbsp;</div>
                        </div>
                     </div>
                  </div>
                  <div class="col-md-4 col-xs-12">
                     <div class="panel panel-widget panel-red">
                        <div class="panel-heading" style="height: 112px;">
                           <div class="row">
                              <div class="col-xs-12">
                                <p>Content</p>
                              </div>
                              <div class="icon fa fa-file fa-3x">&nbsp;</div>
                           </div>
                        </div>
                        <div class="panel-footer">
                           <div class="clearfix">&nbsp;</div>
                        </div>
                     </div>
                  </div>
                  <div class="col-xs-12 col-md-4">
                     <div class="panel panel-widget panel-green">
                        <div class="panel-heading" style="height: 112px;">
                           <div class="row">
                              <div class="col-xs-12">
                              	<p>Content</p>
                              </div>
                              <div class="icon fa fa-key fa-3x">&nbsp;</div>
                           </div>
                        </div>
                        <div class="panel-footer">
                           <div class="clearfix">&nbsp;</div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="tab-pane" id="tabs-tab-2" role="tabpanel">
            <div class="tab-pane-content">
               <div class="row">
                  <div class="col-xs-12">
                  	<p>Content</p>
                  </div>
               </div>
            </div>
         </div>
         <div class="tab-pane active" id="tabs-tab-3" role="tabpanel">
            <div class="tab-pane-content">
               <p>Content</p>
            </div>
         </div>
         <div class="tab-pane" id="tabs-tab-4" role="tabpanel">
            <div class="tab-pane-content">Tab 4 Content</div>
         </div>
      </div>
   </section>
</div>

**Comment by TCURT15** [comment]
<div class="col-lg-9 col-xs-12">
   <section>
      <div class="bootstrap-tabs" data-tab-set-title="tabs">
         <ul class="nav nav-tabs nav-justified" role="tablist">
            
            <li role="presentation"><a aria-controls="tabs-tab-1" aria-expanded="false" class="tab-link" data-toggle="tab" href="#tabs-tab-1" role="tab">Tab 1</a></li>
            <li role="presentation"><a aria-controls="tabs-tab-2" aria-expanded="false" class="tab-link" data-toggle="tab" href="#tabs-tab-2" role="tab">Tab 2</a></li>
            <li class="active" role="presentation"><a aria-controls="tabs-tab-3" aria-expanded="true" class="tab-link" data-toggle="tab" href="#tabs-tab-3" role="tab">Tab 3</a></li>
            <li role="presentation"><a aria-controls="tabs-tab-4" aria-expanded="false" class="tab-link" data-toggle="tab" href="#tabs-tab-4" role="tab">Tab 4</a></li>
         </ul>
      </div>
      <div class="tab-content">
         
         <div class="tab-pane" id="tabs-tab-1" role="tabpanel">
            <div class="tab-pane-content">
               <h3>&nbsp;</h3>
               <h3>Quick Links</h3>
               <div class="row">
                  <div class="col-xs-12 col-md-4">
                     <div class="panel panel-widget panel-orange">
                        <div class="panel-heading" style="height: 112px;">
                           <div class="row">
                              <div class="col-xs-12">
                                <p>Content</p>
                              </div>
                           </div>
                        </div>
                        <div class="panel-footer">
                           <div class="clearfix">&nbsp;</div>
                        </div>
                     </div>
                  </div>
                  <div class="col-md-4 col-xs-12">
                     <div class="panel panel-widget panel-red">
                        <div class="panel-heading" style="height: 112px;">
                           <div class="row">
                              <div class="col-xs-12">
                                <p>Content</p>
                              </div>
                              <div class="icon fa fa-file fa-3x">&nbsp;</div>
                           </div>
                        </div>
                        <div class="panel-footer">
                           <div class="clearfix">&nbsp;</div>
                        </div>
                     </div>
                  </div>
                  <div class="col-xs-12 col-md-4">
                     <div class="panel panel-widget panel-green">
                        <div class="panel-heading" style="height: 112px;">
                           <div class="row">
                              <div class="col-xs-12">
                              	<p>Content</p>
                              </div>
                              <div class="icon fa fa-key fa-3x">&nbsp;</div>
                           </div>
                        </div>
                        <div class="panel-footer">
                           <div class="clearfix">&nbsp;</div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="tab-pane" id="tabs-tab-2" role="tabpanel">
            <div class="tab-pane-content">
               <div class="row">
                  <div class="col-xs-12">
                  	<p>Content</p>
                  </div>
               </div>
            </div>
         </div>
         <div class="tab-pane active" id="tabs-tab-3" role="tabpanel">
            <div class="tab-pane-content">
               <p>Content</p>
            </div>
         </div>
         <div class="tab-pane" id="tabs-tab-4" role="tabpanel">
            <div class="tab-pane-content">Tab 4 Content</div>
         </div>
      </div>
   </section>
</div>

**Comment by TCURT15** [comment]
[tabs.txt](https://github.com/sealocal/ckeditor-bootstrap-tabs/files/476921/tabs.txt)

**Comment by sealocal** [comment]
If you could repeat the steps that you took to modify the HTML, then there might be a solution for preventing malformed HTML.

This is your HTML for the tabs, without the custom content.

```html
<div class="bootstrap-tabs" data-tab-set-title="tabs">
   <ul class="nav nav-tabs nav-justified" role="tablist">
      <!-- add tabs here -->
      <li>
         <a aria-controls="tabs-tab-1" class="tab-link" data-toggle="tab" href="#tabs-tab-1" role="tab">Tab 1</a>
      </li>
      <li>
         <a aria-controls="tabs-tab-2" class="tab-link" data-toggle="tab" href="#tabs-tab-2" role="tab">Tab 2</a>
      </li>
      <li>
         <a aria-controls="tabs-tab-3" class="tab-link" data-toggle="tab" href="#tabs-tab-3" role="tab">Tab 3</a>
      </li>
      <li class="active">
         <a aria-controls="tabs-tab-4" class="tab-link" data-toggle="tab" href="#tabs-tab-4" role="tab">Tab 4</a>
      </li>
   </ul>
</div>

<div class="tab-content">
   <!-- add tab panels here -->
   <div class="tab-pane" id="tabs-tab-1" role="tabpanel">

   </div>
   <div class="tab-pane" id="tabs-tab-2" role="tabpanel">

   </div>
   <div class="tab-pane" id="tabs-tab-3" role="tabpanel">

   </div>
   <div class="tab-pane" id="tabs-tab-4" role="tabpanel">

   </div>
</div>
```

Notice how `<div class="tab-content">` is outside of `<div class="bootstrap-tabs" data-tab-set-title="tabs">`.  I do not know how you were able to modify the content to this state, but that is the root cause of the error you are seeing.

This is a sample of well-formed HTML. The `<div class="bootstrap-tabs" data-tab-set-title="tabs">` portion is outside of the main div. You can find this sample in the repo. https://github.com/sealocal/ckeditor-bootstrap-tabs/blob/v1.1/sample/bootstrapTabs.html

```html
<div class="bootstrap-tabs" data-tab-set-title="sample">
  <ul class="nav nav-tabs" role="tablist">
    <!-- add tabs here -->
    <li class="active" role="presentation">
      <a aria-controls="sample-tab-1" class="tab-link" data-bypass="true" data-toggle="tab" href="#sample-tab-1-name" role="tab">Tab 1 Name</a>
    </li>
    <li role="presentation">
      <a aria-controls="sample-tab-2-name-name" class="tab-link" data-bypass="true" data-toggle="tab" href="#sample-tab-2-name-name" role="tab">Tab 2 Name</a>
    </li>
    <li role="presentation">
      <a aria-controls="sample-tab-3-name" class="tab-link" data-bypass="true" data-toggle="tab" href="#sample-tab-3-name" role="tab">Tab 3 Name</a>
    </li>
    <li class="active" role="presentation">
      <a aria-controls="sample-tab-4-name" class="tab-link" data-bypass="true" data-toggle="tab" href="#sample-tab-4-name" role="tab">Tab 4 Name</a>
    </li>
  </ul>
  <div class="tab-content">
    <!-- add tab panels here -->
    <div class="tab-pane" id="sample-tab-1-name" role="tabpanel">
      <div class="tab-pane-content">Tab 1 Content</div>
    </div>
    <div class="tab-pane" id="sample-tab-2-name" role="tabpanel">
      <div class="tab-pane-content">Tab 2 Content</div>
    </div>
    <div class="tab-pane" id="sample-tab-3-name" role="tabpanel">
      <div class="tab-pane-content">Tab 3 Content</div>
    </div>
    <div class="tab-pane active" id="sample-tab-4-name" role="tabpanel">
      <div class="tab-pane-content">Tab 4 Content</div>
    </div>
  </div>
</div>
```
