### ISSUE TITLE
tabs doesn't work in any browser

### ISSUE THREAD

**Issue by rebwar** [sealocal/ckeditor-bootstrap-tabs#15]
After i create some tabs and click on preview button , the tabs are displayed but only last tab is active and others doesn't work

**Comment by sealocal** [comment]
You'll have to provide more information than that.  Are you accessing the demo page when you have these problems? Is this with your own web page? Are you using the latest release? Are there any JS errors reported? Perhaps a screenshot would help.

**Comment by rebwar** [comment]
Dear sealocal, thank u for replay, all of my ckeditor files updated and download it from ckeditor website 
here is my html file:
[1.txt](https://github.com/sealocal/ckeditor-bootstrap-tabs/files/679022/1.txt)
and here is my project solution:
![untitled](https://cloud.githubusercontent.com/assets/1691770/21570060/c48e6b4e-ced7-11e6-90f7-6524f5c7a8ef.png)

**Comment by rebwar** [comment]
Dear sealocal,
my issue is solved in Real project 
Many thanks
