### ISSUE TITLE
Bootstrap tabs in page are not functional when ckeditor is in the page too

### ISSUE THREAD

**Issue by FranckyLFS** [sealocal/ckeditor-bootstrap-tabs#16]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Insert bootstrap tabs markup in the page's body.
2. Insert a small form with ckeditor in the same page.
3. Try to use the bootstrap tabs of the page's body.

### Expected result

The bootstrap tabs of the page's body should be functional as well as the bootstrap tabs inside ckeditor.
```
if (typeof(CKEDITOR) == 'object') {
  var ckeditorInstances = CKEDITOR.instances;
  if (ckeditorInstances) {
    $.each(ckeditorInstances, function (i) {
      if (ckeditorInstances[i].document) {
        var $tabComponents = $(ckeditorInstances[i].document.$.body).find('.bootstrap-tabs');
        tabsInit($tabComponents);
      } else {
        ckeditorInstances[i].on('instanceReady', function (instanceReadyEventObj) {
          var editorInstanceData = ckeditorInstances[i].document.getBody();
          var $tabComponents = $(editorInstanceData.$).find('.bootstrap-tabs');
          tabsInit($tabComponents);
        });
      }

    });
  }
} else {
  var $viewTabs = $('.bootstrap-tabs', context);
  if ($viewTabs.length > 0) {
    tabsInit($viewTabs);
  }
}
```
I think that the last "else" could be removed to always execute that part.

### Actual result

Only the bootstrap tabs inside ckeditor are functional.

## Other details

* CKEditor version: 4.6.2
* Installed CKEditor plugins: https://ckeditor.com/cke4/addon/bootstrapTabs

**Comment by sealocal** [comment]
Thanks for the idea. This behavior must be handled at the application level.  The plugin should not initialize tabs outside of an editor instance - that behavior is outside the responsibility of a plugin.
