### ISSUE TITLE
Deeper l10n

### ISSUE THREAD

**Issue by smartcorestudio** [sealocal/ckeditor-bootstrap-tabs#2]
I'd like to add a translation, but now only a couple of captions can be translated ("title", "invalidTabs"). Do you have any plans for deeper l10n?

**Comment by sealocal** [comment]
Yes, I would like to build out the translations further, but last time I attempted to set up translations for the plugin, the language files would not load.  I made the attempt in a larger application, but I'll make another attempt with a static page to see if I can narrow down any JS errors and determine what was wrong with my first attempt.  So, currently, not even the "title" and "invalidTabs" work without further configuration.

**Comment by smartcorestudio** [comment]
OK! Please let me know if you'll ever decide to make the translations. I'll be glad to add a translation!

**Comment by sealocal** [comment]
Great! You can list your trenaslaions here or send a pull request if you like. Otherwise, I'll let you know when I modify and set up the translations correctly.

**Comment by smartcorestudio** [comment]
I think I'll just make a pull request based on `en.js` when everything is ready. And I hope some other people will add more translations in the future.

**Comment by sealocal** [comment]
l10n is now working as expected and there are more options for defining translations. Thanks!

**Comment by smartcorestudio** [comment]
Thanks! I've created a pull. You can merge it if you want
