### ISSUE TITLE
Set Up Static Demo Page

### ISSUE THREAD

**Issue by sealocal** [sealocal/ckeditor-bootstrap-tabs#3]
I intend to build a demo page for this plugin.  It will include the default CKEditor configuration/installation [and the ckeditor-bootstrap-tabs plugin].

I suppose I can do this with GitHub pages.

**Comment by smartcorestudio** [comment]
Great news! I think this plugin can be useful for many developers

**Comment by sealocal** [comment]
There is now a demo page at http://sealocal.github.io/ckeditor-bootstrap-tabs .
