### ISSUE TITLE
Improve Installation and Configuration Instructions

### ISSUE THREAD

**Issue by sealocal** [sealocal/ckeditor-bootstrap-tabs#5]
The README and Demo page should show code examples for adding the Bootstrap CSS and JS for an editor instance.  With the Classic editor, styles are not inherited; with the inline editor, styles are inherited from the containing page.

**Comment by wsamson** [comment]
It would also be helpful to include instructions on adding the 'instanceReady' css and js. Being able to click to navigate between tabs in CKEditor is something I'm currently struggling with.

So far I've been unable to successfully implement your plugin in Drupal 7. I'd love to use it, your plugin example is far superior to the [one I'm currently using](http://ckeditor.com/addon/bootstrapTab) for bootstrap tabs. The plugin I'm currently using doesn't allow for easy modification of tabbed content.

**Comment by sealocal** [comment]
@wsamson This is the best implementation I've been able to compose.  Have you tried something like this?

``` html
<form>
<textarea id="ckeditor-bootstrap-tabs-demo" name="ckeditor-bootstrap-tabs-demo" rows="10" cols="80">
  Placeholder
</textarea>
<script>
  // Replace the <textarea id="ckeditor-bootstrap-tabs-demo"> with a CKEditor
  // instance, using default configuration.
  // Enable local "bootstrapTabs" plugin from /ckeditorPlugins/bootstrapTabs/ folder.
  CKEDITOR.plugins.addExternal( 'bootstrapTabs', '/ckeditor-bootstrap-tabs/ckeditorPlugins/bootstrapTabs/', 'plugin.js' );

  // extraPlugins needs to be set too.
  CKEDITOR.replace( 'ckeditor-bootstrap-tabs-demo', {
    extraPlugins: 'bootstrapTabs',
    contentsCss: [ 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css' ],
    on: {
      instanceReady: loadBootstrap,
      mode: loadBootstrap
    }
  });

  // Add the necessary jQuery and Bootstrap JS source so that tabs are clickable.
  // If you're already using Bootstrap JS with your editor instances, then this is not necessary.
  function loadBootstrap(event) {
    var jQueryScriptTag = document.createElement('script');
    var bootstrapScriptTag = document.createElement('script');

    jQueryScriptTag.src = 'https://code.jquery.com/jquery-1.11.3.min.js';
    bootstrapScriptTag.src = 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js';

    var editorHead = event.editor.document.$.head;

    editorHead.appendChild(jQueryScriptTag);
    jQueryScriptTag.onload = function() {
      editorHead.appendChild(bootstrapScriptTag);
    };
  }
</script>
</form>
```

**Comment by wsamson** [comment]
@sealocal thanks for the quick reply, Mike. I'll work through this and see what I can do. Out of curiosity, have you tried implementing your plugin, specifically, within the [CKEditor module](https://www.drupal.org/project/ckeditor) for Drupal 7?

**Comment by sealocal** [comment]
@wsamson No, I am not familiar with Drupal at all.  Feel free to post any error messages or description of the problem that you're encountering.  You can post it here or in a new issue if you think it's really specific to Drupal.  Perhaps someone else is trying to add the plugin to their Drupal setup as well and having trouble.

One more thing - the plugin was recently updated with an `allowedContent` filter to fix part of the problem in #7.

**Comment by wsamson** [comment]
@sealocal Thanks Mike! I'll let you know what issues I encounter.

**Comment by wsamson** [comment]
@sealocal Would it be possible for you to provide a complete and working CKEditor with this installed? I'm having quite a bit of trouble getting it to work.

**Comment by wsamson** [comment]
@sealocal One with the necessary jQuery and Bootstrap JS source so that tabs are clickable would be amazing... no worries if not.

**Comment by sealocal** [comment]
@wsamson I feel your frustration. I've struggled with docs and configuration with CKEditor.  I'm not quite sure what you mean by "complete."  The demo page is a complete editor, and the above HTML/JS is the code that creates the editor on the demo page.

Are you able to load the plugin, add tabs via the dialog, and then see the tabs in the editor?  If so, do they appear styled as Bootstrap?

What browser(s) are you using?
What CKEditor version?
Are you using CKEditor `inline` or `replace`?
If you can see tabs, do you see error messages in the JS console when you click on tabs?

**Comment by wsamson** [comment]
@sealocal Hi Mike, thanks for the reply and sorry that I wasn't more clear. I was hoping you could provide a zip file of the plugin added and configured with the [CKEditor files source files](http://ckeditor.com/download) - so I can see it properly added.

Keep in mind, I'm trying to get this working with the CKEditor module for Drupal 7. So far, I've been unable to get it to work - nothing appears after I load the plugin so I can't provide any error messages, etc. I've been using Chrome and Firefox.

I do really appreciate your help, CKEditor has been a HUGE headache for both myself and my content administrators.

**Comment by sealocal** [comment]
I do not understand how the Drupal module installation differs from other web frameworks or static pages.  Do you need a `.info` or `.module` file?

Do you understand how to use the zip file build tool (the one that you linked to above) and use the resulting zip file to install CKEditor with Drupal?  Would you mind trying to download it and adding the ["Bootstrap Tabs"](http://ckeditor.com/addon/bootstrapTabs) addon to that zip build?
