### ISSUE TITLE
Switching into source mode and back

### ISSUE THREAD

**Issue by smartcorestudio** [sealocal/ckeditor-bootstrap-tabs#7]
Hey again! Seems like I've found a bug. Try to switch into the source mode and back in your demo. Tabs will be converted into `<ul><li>...</li></ul>` and their content - to `<p>...</p>`

**Comment by sealocal** [comment]
I think this is a problem with the setup for the editor on the demo page. I believe it can be solved by adding Bootstrap to the editor's stylesheets when the source mode is toggled.  A `mode` event handler can be added to do that.

**Comment by sealocal** [comment]
This actually has more to do with the allowedContent filter.  Seems to be fixed with 9953870e1a24b9cdd01bc125a31fbe95e85ea5d8, 1ae2d4b5cdc583c5c3094c691663f0ed78632ec5, and 80cf7c12e3bc093ede0ff40c9da18182fab3d022.

**Comment by smartcorestudio** [comment]
The only thing I've found in your demo http://sealocal.github.io/ckeditor-bootstrap-tabs/ is: after switching to the source and back tabs now display OK, but doesn't function. I mean that clicking the tab doesn't open it's content in the editor

**Comment by sealocal** [comment]
Hmmm, looks like the Bootstrap JS isn't loading.

**Comment by sealocal** [comment]
Fixed!
